### ISSUE TITLE
About details of AIR_TINY dataset

### ISSUE THREAD

**Issue by kimphys** [yoshall/AirFormer#1]
Thank you for great works! 

I just explore your codes, but I have a question just before.

Could you explain details of AIR_TINY dataset? Especially I want to know 16 features derived from ./data/AIR_TINY/train.npz

(20, 24, 1085, 16)
I guess 20 is num. of instances, 24 is num. of time steps, and 1085 is num. of stations.
But I didn't understand what 20 means.

Thanks

**Comment by JingweiZuo** [comment]
Based on the DeepAir paper, I believe that the last element '16' represents the number of AQI features from neighboring regions. You can confirm this by checking Section 3 of the DeepAir paper. 

However, it's unfortunate that the authors did not provide code for preparing these features.

**Comment by ZzhuangIsCharming** [comment]
你好兄弟，请问你最近数据集处理这方面有进展吗？我也遇到了数据集处理的难题，可以一起交流交流吗？

**Comment by ZzhuangIsCharming** [comment]
Hello brother, have you made any progress in data set processing recently? I also encountered the problem of data set processing. Can we communicate together?

**Comment by yoshall** [comment]
<img width="999" alt="微信图片_20231209214556" src="https://github.com/yoshall/AirFormer/assets/40017013/730346e7-ef00-4a1a-8810-00e162c4feec">
