### ISSUE TITLE
Request for complete dataset

### ISSUE THREAD

**Issue by luojueling** [yoshall/AirFormer#3]
I am a student studying machine learning and environmental science, and I recently read your paper "AirFormer: Predicting Nationwide Air Quality in China with Transformers." Your work on predicting air quality in China with Transformers is fascinating and has the potential to make a significant impact in environmental research.

I noticed that you have released a small part of the dataset used in your paper. However, I am writing to request the complete dataset used in your experiments. I am extremely interested in replicating your experiments and would like to gain a deeper understanding of your approach.

As an aspiring researcher in this field, I believe that having access to the complete dataset will be crucial for me to reproduce your experiments accurately. I assure you that any data you provide will be used for research and educational purposes only.

I understand that your time is valuable, and I would greatly appreciate it if you could spare some time to respond to my request. Additionally, if it is convenient for you, could you also give me some guidance and suggestions on how to approach a similar problem in environmental science with machine learning?

Thank you for your contributions to the field, and I look forward to hearing from you soon.

Best regards

**Comment by ZzhuangIsCharming** [comment]
Hello brother, have you made any progress in data set processing recently? I also encountered the problem of data set processing. Can we communicate together?

**Comment by yoshall** [comment]
We plan to release the dataset in 2024. Thank you for your attention!

**Comment by patel-zeel** [comment]
Dear @yoshall, any update on the full dataset? 

Is it possible for anyone to follow the same steps as you and download it from some public portal? If yes, can you please help with those steps?
